name: Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl

      - uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          folder: ./docs/build
          clean: true
          git-config-email: bot@swc.rs
          repository-name: SaremS/AdvancedBoosting.jl
          commit-message: "Update docs"
          single-commit: true
